openapi: 3.0.0
info:
  title: test
  version: '1.0'
  description: test description
paths:
  https://onchainpay.xyz/api-gateway/test-signature:
    post:
      tags:
        - base
      security: []
      summary: Проверка корректности подписи x-api-signature
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestSignatureResponse'
  https://onchainpay.xyz/api-gateway/available-currencies:
    post:
      tags:
        - base
      security: []
      summary: Получение монет доступных для приема/отправки транзакций
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableCurrenciesResponse'
components:
  schemas:
    TestSignatureResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        response:
          type: object
          properties:
            errors:
              type: array
              items:
                type: string
                example: Signature check failed
              example: []
            checkSignatureResult:
              type: boolean
              example: true
            rightSignature:
              type: string
              example: 69e377f1f8759e9810ce3a4c033c87036cd9affaf3ef68ad43799a425ce88da2
            signature:
              type: string
              example: 69e377f1f8759e9810ce3a4c033c87036cd9affaf3ef68ad43799a425ce88da2
            receivedBody:
              type: string
              example: '{"nonce":1643881363781}'
    AvailableCurrencyNetwork:
      type: object
      properties:
        name:
          description: Имя сети
          type: string
          example: ethereum
        allowDeposit:
          description: Флаг указывает доступен ли прием входящих транзакций в данный момент
          type: boolean
        allowWithdrawal:
          description: >-
            Флаг указывает доступна ли отправка исходящих транзакций в данный
            момент
          type: boolean
        withdrawalFee:
          description: Стоимость исходящей транзакции
          type: string
          example: '0.0005'
        withdrawalMin:
          description: Минимальная сумма для создания исходящей транзакции
          type: string
          example: '0.001'
        addressRegex:
          description: Регулярное выражение для валидации адресов
          type: string
          example: ^(0x)[0-9A-Fa-f]{40}$
        tagRegex:
          description: >-
            Регулярное выражение для валидации тега(memo) адреса. Может быть
            пустая строка в случаях когда сеть не поддерживает работу с тегом
          type: string
          example: ''
    AvailableCurrency:
      type: object
      properties:
        currency:
          description: Тикер монеты
          type: string
          example: ETH
        allowDeposit:
          description: Флаг указывает доступен ли прием входящих транзакций в данный момент
          type: boolean
        allowWithdrawal:
          description: >-
            Флаг указывает доступна ли отправка исходящих транзакций в данный
            момент
          type: boolean
        networks:
          description: Список сетей в которых возможен прием/отправка транщакций
          type: array
          items:
            $ref: '#/components/schemas/AvailableCurrencyNetwork'
    AvailableCurrenciesResponse:
      type: object
      properties:
        success:
          type: boolean
          example: 'true'
        response:
          type: array
          items:
            $ref: '#/components/schemas/AvailableCurrency'
