openapi: 3.0.0
info:
  title: qweEWQ
  version: '1.0'
  description: main description
paths:
  /test-signature:
    post:
      tags:
        - test-signature
      security: []
      summary: test 2
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestSignatureResponse'
components:
  schemas:
    TestSignatureResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        response:
          type: object
          properties:
            errors:
              type: array
              items:
                type: string
                example: Signature check failed
              example: []
            checkSignatureResult:
              type: boolean
              example: true
            rightSignature:
              type: string
              example: 69e377f1f8759e9810ce3a4c033c87036cd9affaf3ef68ad43799a425ce88da2
            signature:
              type: string
              example: 69e377f1f8759e9810ce3a4c033c87036cd9affaf3ef68ad43799a425ce88da2
            receivedBody:
              type: string
              example: '{"nonce":1643881363781}'
