openapi: 3.0.0
info:
  title: t(:title)
  version: '1.0'
  description: main description
paths:
  /test-signature:
    post:
      tags:
        - test-signature
      security: []
      summary: test 1
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: schemas.yaml#/TestSignatureResponse
components:
  responses: {}
